name: Build

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 21
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        distribution: adopt
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build
